config/routes.rb
Rails.application.routes.draw do
  root 'forms#new'
  devise_for :users
  devise_scope :admin do
    resources :users, only: [:show]
  end
  resources :forms, only: [:new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/form.rb
class Form < ApplicationRecord

  enum category: ['Android Developer', 'Web Developer', 'Problem Solver', 'Other']

  VALID_MOBILE_REGEX = /^[0-9]{10}$/

  NAME_REGEX = /^[a-zA-Z\d\s]*$/

  validates_presence_of :first_name, :last_name, :category, :phone

  validates :first_name, format: { with: NAME_REGEX, multiline: true }, allow_blank: true, length: { maximum: 30 }
  validates :last_name, format: { with: NAME_REGEX, multiline: true }, allow_blank: true, length: { maximum: 30 }

  validates :phone, format: { with: VALID_MOBILE_REGEX, multiline: true }, allow_blank: true, length: { maximum: 10 }

  validates :category, inclusion: {in: categories.keys}, allow_blank: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def render_404
    respond_to do |format|
      format.html do
        render file: Rails.root.join("public", "404"), layout: false, status: "404"
      end
      format.any { head :not_found }
    end
  end
end

app/controllers/forms_controller.rb
class FormsController < ApplicationController

  before_action :re_route

  def new
    @form = Form.new
  end

  def create
    @form = Form.new(form_params)
    if @form.save
      flash[:success] = 'You successfully reserved a spot!'
      redirect_back fallback_location: root_path
    else
      render :new
    end
  end

  private

  def form_params
    params.require(:form).permit(:first_name, :last_name, :category, :phone)
  end
  
  def re_route
    redirect_to user_path(current_user.id) if current_user
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :prevent_views

  def show
    @user = User.find(params[:id])
    @list = Form.all
    @total = @list.count
    @android = Form.where("category = ?", '0').count
    @web = Form.where("category = ?", '1').count 
    @problem = Form.where("category = ?", '2').count 
    @other = Form.where("category = ?", '3').count   
  end

  private 

  def prevent_views
    render_404 unless current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/forms_helper.rb
module FormsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/forms/new.html.erb
<style>
  body {
    background-color: #373a40 !important;
  }
</style>


<div class="container">
  <h4 class="text-center m-t-50 text-white"> GIMPA APP CHALLENGE </h4>
  <div class="row m-t-40">
    <div class="col-md-4 col-lg-4 d-flex">
      <div class="card" style="width: 25rem; margin-bottom: 20px;">
        <div class="card-body">
          <h5 class="card-title">Hackathon Criteria</h5>
          <hr>
          <p class="card-text">
            The list below shows the categories of apps which can be submitted/presented there
          </p>
            <ul type="circle" class="card-text">
              <li>Education Sector</li>
              <li>Health Sector</li>
              <li>Finance Sector</li>
              <li>Agriculture Sector</li>
            </ul>
          <hr>
          <p class="card-text">Other participating schools includes: </p>
          <ul type="square">
            <li>Kwame Nkrumah University of Science and Technology (KNUST)</li>
            <li>Ashesi University</li>
            <li>The University of Ghana, Legon (UG)</li>
            <li>Wisconsin University</li>
            <li>Ghana Telecom University</li>
            <li>Methodist University</li>
            <li>Bluecrest University College</li>
            <li>University of Professional Studies (UPS)</li>
          </ul>
        </div>
      </div>
    </div>
    <div class="col-md-2 col-lg-2"></div>
    <div class="col-md-6 col-lg-6">

        <div class="card" style="width: 25rem;">
          <div class="card-body">

            <%= form_for(@form, url: forms_path) do |f| %>

              <div class="text-center">
                <h5 class="text-uppercase" style="margin-bottom: 2px;">Reservation Form</h5>
                <hr>
                <small style="color: red; margin-bottom: 10px !important;">Event Date: 17th April, 2018.</small>
                <hr>
              </div>
              <%= render 'shared/error_message', object: f.object %>
              <%= render 'shared/flash_message' %>

              <div class="form-group">
                <%= f.label :first_name %>
                <%= f.text_field :first_name, class: 'form-control', placeholder: 'e.g Nicholina' %>
              </div>

              <div class="form-group">
                <%= f.label :last_name %>
                <%= f.text_field :last_name, class: 'form-control', placeholder: 'e.g Doe' %>
              </div>

              <div class="form-group">
                <%= f.label :phone %>
                <%= f.telephone_field :phone, class: 'form-control', placeholder: 'e.g 0574017761', maxlength: 10 %>
              </div>

              <div class="form-group">
                <%= f.label :Category %>
                <%= f.select :category, options_for_select(Form.categories.keys), {prompt: "Select Category"}, class: "form-control" %>
              </div>

              <%= f.submit "Submit", class: 'btn btn-primary btn-block' %>
            <% end %>
          </div>
        </div>

    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">

  <head>
    <title>GIMPA Appchallenge</title>
    <%= csrf_meta_tags %>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
      <meta name="description" content="Registering for GIMPA APP CHALLENGE" />
      <meta name="author" content="Miracle Anyanwu (Polygod)">
      <script defer src="https://use.fontawesome.com/releases/v5.0.7/js/all.js"></script>
      <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>

      <%= render 'shared/footer' %>
        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
          crossorigin="anonymous"></script>
        <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </body>

</html>

app/views/shared/_devise_flash.html.erb
<% if flash[:notice] %>
	<div class="alert alert-info">
		<button type="button" class="close">
			&times;
		</button>
		<%= notice %>
	</div>
<% end %>

<% if flash[:alert] %>
	<div class="alert alert-danger">
		<button type="button" class="close">
			&times;
		</button>
		<%= flash[:alert] %>
	</div>
<% end %>

app/views/shared/_error_message.html.erb
<% if object.errors.any? %>

    <div id="error_explanation">

      <div class="alert alert-danger" role="alert">
         <span style="font-size: 15px;"> <%= pluralize(object.errors.count, "error") %> prohibited this form from being sent. </span>
          <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <ul>
          <% object.errors.full_messages.each do |msg| %>
            <li>
              <span style="font-size: 13px;"> <%= msg %> </span>
            </li>
          <% end %>
      </ul>
      </div>
    </div>
<% end %>

app/views/shared/_flash_message.html.erb
<% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %> alert-dismissible" role="alert">
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true"> &times; </span>
          </button>
          <%= message %>
        </div>
<% end %>

app/views/shared/_footer.html.erb
<!-- Footer -->
<footer class="m-t-30">
  <div class="container">
    <ul class="list-inline">
      <li class="list-inline-item">

      </li>
      <li class="footer-menu-divider list-inline-item"></li>
      <li class="list-inline-item">

      </li>
      <li class="footer-menu-divider list-inline-item"></li>
      <li class="list-inline-item">

      </li>
      <li class="footer-menu-divider list-inline-item"></li>
      <li class="list-inline-item">

      </li>
      <li class="footer-menu-divider list-inline-item"></li>
      <li class="list-inline-item">
      </li>
    </ul>
    <p class="copyright text-muted small text-center">
      <span class="text-white">&copy; 2018. Crafted with
        <i class="fas fa-heart" style="color: red;"></i> by</span>
      <a href="https://polymathwhiz.github.io" target="_blank">
        <b style="color: #669dd8 !important;">Polygod</b>
      </a>
    </p>
  </div>
</footer>

app/views/users/show.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container">
    <a class="navbar-brand" href="#">GIMPA APP CHALLENGE</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
      aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
      </ul>
      <ul class="navbar-nav">
        <li class="nav-item active">
          <a href="<%= destroy_user_session_path %>" data-method="delete" rel="nofollow" class="nav-link">Sign Out</a>
        </li>
      </ul>
    </div>
</nav>


<div class="container">
  <div class="row">
    <div class="col-md-2" style="margin-top: 20px;">
      Android:
      <span>
        <%= @android %>
      </span>
      <br> Web:
      <span>
        <%= @web %>
      </span>
      <br> Problem Solvers:
      <span>
        <%= @problem %>
      </span>
      <br> Other:
      <span>
        <%= @other  %>
      </span>
      <br> Total:
      <span>
        <%= @total %>
      </span>
    </div>
    <div class="col-md-9">
      <%= render 'shared/flash_message' %>
        <center>
          <h4 style="margin-top: 20px; margin-bottom: 20px;">Registered Students</h4>
        </center>
        <table class="table">
          <thead>
            <tr>
              <th>#</th>
              <th>First Name</th>
              <th>Last Name</th>
              <th>Phone number</th>
              <th>Category</th>
            </tr>
          </thead>

          <tbody>
            <% @list.each_with_index do |list, count|%>
              <% count += 1 %>
                <tr>
                  <th scope="row">
                    <%= count %>
                  </th>
                  <td>
                    <%= list.first_name %>
                  </td>
                  <td>
                    <%= list.last_name %>
                  </td>
                  <td>
                    <%= list.phone %>
                  </td>
                  <td>
                    <%= list.category %>
                  </td>
                </tr>
                <% end %>
          </tbody>
        </table>
    </div>
  </div>
</div>
</div>